name:                aoc
version:             0.1.0.0
github:              "jborkowski/aoc"
license:             BSD3
author:              "Jonatan Borkowski"
maintainer:          "jonatan.borkowski@protonmail.com"
copyright:           "2019 Jonatan Borkowski"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/jborkowski/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- split
- attoparsec
- parsec

library:
  source-dirs: src

executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc

tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
    - hspec
